### ISSUE TITLE
账户无法登录？

### ISSUE THREAD

**Issue by coLATin** [shaonianzhentan/cloud_music#10]
PVE虚拟ubuntu做服务环境，HA和相关服务都在docker里面跑，安装后无法登录账户，网易云音乐的API是通的。并且FM列表可以播放，说明内外网无问题。
点击登录输入用户ID无效，无任何反应。
![1585118275603](https://user-images.githubusercontent.com/749762/77508707-4802f000-6ea6-11ea-8693-784bf79179fd.jpg)

<img width="496" alt="WechatIMG21" src="https://user-images.githubusercontent.com/749762/77508748-62d56480-6ea6-11ea-8c71-aaa4fdeaa213.png">

**Comment by shaonianzhentan** [comment]
最新版已经修复了这个问题
