### ISSUE TITLE
播放歌单 推荐 等都是空的  

### ISSUE THREAD

**Issue by yhwl8888** [shaonianzhentan/cloud_music#14]
media_player:
  - platform: mpd
    host: 192.168.50.196
    port: 6600 
  - platform: ha_cloud_music
    api_url: 'http://localhost:3009'
    sidebar_title: 云音乐
    sidebar_icon: mdi:music
    show_mode: fullscreen
    uid: 
    user: yhwl12222@163.com
    passwowrd: 666666
    tts_before_message: '主人：'
    tts_after_message: '。我是爱你的小喵'
    tts_mode: 4
    is_voice: true
    is_notify: true
    is_debug: true

搜索 我的歌单  登录都用不了  只有FM电台可以听

**Comment by shaonianzhentan** [comment]
一般是你的接口有问题，才会出现这种情况
你可以在浏览器里输入你的音乐接口，看看是否正确
