### ISSUE TITLE
感谢分享这样的好东西，最近发现网易云歌单播放时出现问题。

### ISSUE THREAD

**Issue by 1043717432** [shaonianzhentan/cloud_music#16]
不是播放器的问题，是网易云最近不知道加了什么，所有外链的歌单，包括个人的，都只能显示前10首音乐而已。我设置网页页面直接打开歌单地址。以前可以全部都看到。
现在不行了。
也是只有前10首，提示查看更多内容，请下载客户端，希望大神有空能解决一下！

**Comment by sunjx888** [comment]
我也是这样，还没找到原因

**Comment by shaonianzhentan** [comment]
2.5版本已经修复了这个问题
