### ISSUE TITLE
DLAN播放器下不能自动下一首

### ISSUE THREAD

**Issue by sunjx888** [shaonianzhentan/cloud_music#17]
环境：群晖docker Home Assistant 0.110.7，DLNA插件是虫子的，发声设备是斐讯R1。
一首歌播放完切换下一首时会发生各种奇怪的问题，有的时候播放一秒左右就没声音但是进度条在走，有的时候播放一秒左右直接暂停，点了播放没反应或者两个声音一前一后同时播放。

**Comment by shaonianzhentan** [comment]
估计是设备不稳定
这种莫名其妙的问题太多了
我在小度音箱上测试过，目前还没有遇到这样的问题

**Comment by sunjx888** [comment]
ha连接win10的媒体流dlna正常播放，手机连R1的dlna也正常播放，但是ha连R1的dlna就会出现奇怪的化学反应导致不能正常播放下一首音乐。
如果小度能完美运行的话那我准备换个硬件。

**Comment by shaonianzhentan** [comment]
反正就是奇奇怪怪的事情一堆，修不完的BUG😂

**Comment by sunjx888** [comment]
换成了forked-daapd+mpd+AirPlay，目前完美支持，DLNA以后只用来做TTS播放，有用某讯R1音箱的可以借鉴一下（有一说一，这音箱音质不错）
