### ISSUE TITLE
can not log in 

### ISSUE THREAD

**Issue by leoyangt** [shaonianzhentan/cloud_music#18]
Hi 
thanks for your effort and hard work.
I had problem on login .
condition : 
                  1. running HA in docker and raspberry Pi
                  2. install ha_cloud_music thru HACS.
                  3. set up below item in configuration.yaml
But problem : can not log in cloud music.
could you advise some idea?
tks
===========================
  - platform: ha_cloud_music
    api_url: 'http://10.0.0.200:3000'
    sidebar_title: 云音乐
    sidebar_icon: mdi:music
    show_mode: fullscreen
    uid: 100340334

**Comment by shaonianzhentan** [comment]
You need set user and password

Docs: https://github.com/shaonianzhentan/ha_cloud_music/tree/master/docs

**Comment by leoyangt** [comment]
> # Hi
> thanks for your effort and hard work.
> I had problem on login .
> condition :
> 1. running HA in docker and raspberry Pi
> 2. install ha_cloud_music thru HACS.
> 3. set up below item in configuration.yaml
> But problem : can not log in cloud music.
> could you advise some idea?
> tks
> * platform: ha_cloud_music
>   api_url: 'http://10.0.0.200:3000'
>   sidebar_title: 云音乐
>   sidebar_icon: mdi:music
>   show_mode: fullscreen
>   uid: 100340334



> You need set user and password
> 
> Docs: https://github.com/shaonianzhentan/ha_cloud_music/tree/master/docs

Tks for your reply
I did already set usr and password
But still can not log in
==============
  - platform: ha_cloud_music
    api_url: http://localhost:3000/test.html
    sidebar_title: 云音乐
    sidebar_icon: mdi:music
    show_mode: fullscreen
    uid: 100340334
    user: +88693*********
    passwowrd: axcelis1
    tts_before_message: '主人：'
    tts_after_message: '。我是爱你的小喵'
    tts_mode: 4
    is_voice: true
    is_notify: true
    is_debug: true

**Comment by shaonianzhentan** [comment]
Music API Docs： https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=%e7%99%bb%e5%bd%95

You can try to use the login API in your browser

`http://10.0.0.200:3000/login/cellphone?phone=yourPhone&password=yourPassword`
or
`http://10.0.0.200:3000/login?email=yourEmail&password=yourPassword`

**If no problem, it should be completely OK**

If not, I think it is related to countrycode. You can try to modify the code
