### ISSUE TITLE
网页播放器是怎么使用

### ISSUE THREAD

**Issue by maxmib** [shaonianzhentan/cloud_music#20]
请问网页播放器是怎么使用，是浏览器直接播放？

**Comment by shaonianzhentan** [comment]
还没搞完，暂时还有问题

**Comment by shaonianzhentan** [comment]
这是网页播放器的链接： http://IP:8123/ha_cloud_music-web/index.html

在播放器里选择网页播放器，然后在浏览器中打开以上链接，然后就可以播放了

---

但是千万别开多个页面，不然。。。
