### ISSUE TITLE
ncm文件播放不了

### ISSUE THREAD

**Issue by banyip** [shaonianzhentan/cloud_music#24]
如题

**Comment by shaonianzhentan** [comment]
API接口里哪首歌返回了这个格式？

**Comment by shaonianzhentan** [comment]
> 如题

API接口里哪首歌返回了这个格式？把接口地址参数贴出来一下

**Comment by banyip** [comment]
> > 如题
> 
> API接口里哪首歌返回了这个格式？把接口地址参数贴出来一下

/lyric?id=17177324

**Comment by shaonianzhentan** [comment]
这首音乐是MP3格式啊
![image](https://user-images.githubusercontent.com/5294022/95534903-a003dd00-0a19-11eb-8ada-d399037f66ba.png)
