### ISSUE TITLE
google home推送不能自动下一曲

### ISSUE THREAD

**Issue by diamondt5353** [shaonianzhentan/cloud_music#27]
![屏幕截图 2020-10-12 234320](https://user-images.githubusercontent.com/57979092/95765817-f3f61680-0ce4-11eb-8f4c-d511be66429d.png)
![屏幕截图 2020-10-12 234446](https://user-images.githubusercontent.com/57979092/95765822-f6587080-0ce4-11eb-8d8e-54fa4ef7a028.png)

**Comment by diamondt5353** [comment]
![屏幕截图 2020-10-12 234704](https://user-images.githubusercontent.com/57979092/95766032-46cfce00-0ce5-11eb-83de-397dda7cead8.png)

**Comment by shaonianzhentan** [comment]
是播放的时候进度条不跟着动么？
那你检查一下这个名称是客厅的播放器，是否有`media_position`和`media_duration`属性
这两个是控制自动下一曲的关键

**Comment by diamondt5353** [comment]
没有这两属性，推送到客厅能播放，客厅就是Googlehome，应该是google home问题
