### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by GWan1234** [shaonianzhentan/cloud_music#29]
感谢更新维护的这个项目，之前HA没有网页播放器，我尝试安装，虽然曲折，最后成功，各种功能十分牛*。

现在更换设备，再次安装时发现报错，遂来反馈，也可能是我操作问题，望指点。

操作环境：
ubuntu18.04
docker环境安装，具体可看图片。
https://github.com/Tao173/Photos/blob/master/3.jpg
网易的API也是docker环境安装，命令：
docker run -d -p 3000:3000 --name netease_cloud_music_api -e http_proxy= -e https_proxy= -e no_proxy= -e HTTP_PROXY= -e HTTPS_PROXY= -e NO_PROXY= binaryify/netease_cloud_music_api

安装完成报错，找不到切换播放器的接口。
https://github.com/Tao173/Photos/blob/master/2.png
https://github.com/Tao173/Photos/blob/master/1.png

具体HA日志：
https://github.com/Tao173/Photos/blob/master/ha_cloud_music-bug

再次感谢这个项目。

**Comment by shaonianzhentan** [comment]
在设置切换卡里可以选择播放器

**Comment by GWan1234** [comment]
> 在设置切换卡里可以选择播放器

感谢回复

已设置好网页播放器，但是没有声音，查看HA日志有错，Home Assistant 0.116.4

Logger: aiohttp.server
Source: custom_components/ha_cloud_music/api_music.py:159
First occurred: 上午1:06:06 (1 occurrences)
Last logged: 上午1:06:06

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/config/custom_components/ha_cloud_music/api_view.py", line 31, in post
    _result = await mp.api_music.search_playlist(_name)
  File "/config/custom_components/ha_cloud_music/api_music.py", line 159, in search_playlist
    if obj['code'] == 200:
TypeError: 'NoneType' object is not subscriptable

望回复。 @shaonianzhentan

**Comment by shaonianzhentan** [comment]
> > 在设置切换卡里可以选择播放器
> 
> 感谢回复
> 
> 已设置好网页播放器，但是没有声音，查看HA日志有错，Home Assistant 0.116.4
> 
> Logger: aiohttp.server
> Source: custom_components/ha_cloud_music/api_music.py:159
> First occurred: 上午1:06:06 (1 occurrences)
> Last logged: 上午1:06:06
> 
> Error handling request
> Traceback (most recent call last):
> File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
> resp = await task
> File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
> resp = await handler(request)
> File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
> return await handler(request)
> File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
> return await handler(request)
> File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
> return await handler(request)
> File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
> return await handler(request)
> File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
> result = await result
> File "/config/custom_components/ha_cloud_music/api_view.py", line 31, in post
> _result = await mp.api_music.search_playlist(_name)
> File "/config/custom_components/ha_cloud_music/api_music.py", line 159, in search_playlist
> if obj['code'] == 200:
> TypeError: 'NoneType' object is not subscriptable
> 
> 望回复。 @shaonianzhentan

从错误日志看来，是音乐接口不通，没有返回数据导致异常，请仔细检查一下音乐接口是否在HA中调不通的情况
