### ISSUE TITLE
选择播放源“网页播放器”没声音？

### ISSUE THREAD

**Issue by plutosherry** [shaonianzhentan/cloud_music#30]
作者你好！
运行无错误，也能够正常播放uid收藏的音乐，但是：~~~
选择播放源“网页播放器”没声音？
另外选择dlna发现的播放源也没有声音？
不知是我配置的不对还是缺少了什么？

**Comment by shaonianzhentan** [comment]
选择“网页播放器”请先点击蓝色字体的源播放器

**Comment by plutosherry** [comment]
OK了，点击源播放器之后会弹出一个新的嵌入有播放器的页面。能否保留缺省设置（不用每次都要这样操作一番）？又或者自动保留成HA内嵌的网页播放器，而不是弹出一个新的页面？

**Comment by shaonianzhentan** [comment]
> OK了，点击源播放器之后会弹出一个新的嵌入有播放器的页面。能否保留缺省设置（不用每次都要这样操作一番）？又或者自动保留成HA内嵌的网页播放器，而不是弹出一个新的页面？

网页播放器只是我测试用的，不是给你们正式使用的

**Comment by GWan1234** [comment]
原来如此啊。。。。我的可以正常使用了，请问有计划加入网页播放么？？ @shaonianzhentan
