### ISSUE TITLE
每播放一首歌都提示”请重新选择源播放器”，然后进度一直不动，也没有声音

### ISSUE THREAD

**Issue by banyip** [shaonianzhentan/cloud_music#31]
配置文件如下：
default_config:

tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

media_player:
  - platform: mpd
    host: 127.0.0.1
  - platform: ha_cloud_music
    api_url: 'http://localhost:3000'
    sidebar_title: 云音乐
    sidebar_icon: mdi:music
    show_mode: fullscreen
    is_debug: true

recorder:
  exclude:
    entities:
      - media_player.yun_yin_le

**Comment by shaonianzhentan** [comment]
你没配置mpd_host

**Comment by banyip** [comment]
> 你没配置mpd_host

配置了也不行

**Comment by wangyumo85** [comment]
我也遇到了同样的错误，哥们解决了吗

**Comment by shaonianzhentan** [comment]
如果使用中有问题，可以先使用网页播放器测试
实在不懂就看视频：https://www.bilibili.com/video/BV1et4y1a7RU/
