### ISSUE TITLE
内网穿透访问无法播放，前一个版本可以

### ISSUE THREAD

**Issue by GWan1234** [shaonianzhentan/cloud_music#33]
Logger: frontend.js.latest.202011112
Source: components/system_log/__init__.py:193
First occurred: 上午12:05:45 (14 occurrences)
Last logged: 下午5:50:33

https://3#######打吗o.co/ha_cloud_music-web/card/ha_cloud_music.js?v=4.4:10:32 TypeError: null is not an object (evaluating 'this.hass.states[this.entity_id]')
https://3########打吗o.co/ha_cloud_music-web/card/ha_cloud_music.js?v=4.4:10:32 Uncaught TypeError: Cannot read property 'media_player.yun_yin_le' of null
:0:0 Script error.

**Comment by shaonianzhentan** [comment]
这是因为第一次没有缓存的问题，第二次进入就好了
你加载完刷新一下页面就好了

**Comment by GWan1234** [comment]
HA那个app里面点开卡片，无法点击设置、电台、语音等二级菜单.....有机会吗？

**Comment by shaonianzhentan** [comment]
> HA那个app里面点开卡片，无法点击设置、电台、语音等二级菜单.....有机会吗？

如果你是因为点了然后没有东西显示，那是因为要点击文字才可以
