### ISSUE TITLE
我的搜索界面还是老的只有三个选项的界面

### ISSUE THREAD

**Issue by style6** [shaonianzhentan/cloud_music#34]
我的搜索界面还是老的只有三个选项的界面，下载最新的版本，但是插件版本显示的是4.4，但是我看你的视频教程显示4.4.3，是什么问题？
![QQ截图20201217093728](https://user-images.githubusercontent.com/47061418/102427145-b8146000-404b-11eb-9da1-4b0051582117.jpg)

![QQ截图20201217093742](https://user-images.githubusercontent.com/47061418/102427211-dbd7a600-404b-11eb-8d0b-ba31e6153e3d.jpg)

**Comment by shaonianzhentan** [comment]
你要下载master版本
