### ISSUE TITLE
ha的官方APP里插件用不了。

### ISSUE THREAD

**Issue by shidaisky** [shaonianzhentan/cloud_music#35]
HA的官方安卓APP的下载地址为https://github.com/home-assistant/android/releases
我从上述地址下载安装了APP后，在APP里点击云音乐，详情页里没有显示，点击右上角的齿轮进去后，设置里提示“该实体（”media_player.yun_in_le")没有唯一的ID，因此无法由UI管理其设置。…………
这个问题可以解决吗？

**Comment by shaonianzhentan** [comment]
> HA的官方安卓APP的下载地址为https://github.com/home-assistant/android/releases
> 我从上述地址下载安装了APP后，在APP里点击云音乐，详情页里没有显示，点击右上角的齿轮进去后，设置里提示“该实体（”media_player.yun_in_le")没有唯一的ID，因此无法由UI管理其设置。…………
> 这个问题可以解决吗？

你想做什么？

**Comment by hxfdean** [comment]
大佬，我也跟楼主一样，左侧云音乐标签点开一切正常，但是播放没有声音，概览界面点开云音乐，没有设置播放器或者进度条，语音助手等选项。不知道问题出在哪？求救

**Comment by shaonianzhentan** [comment]
> 大佬，我也跟楼主一样，左侧云音乐标签点开一切正常，但是播放没有声音，概览界面点开云音乐，没有设置播放器或者进度条，语音助手等选项。不知道问题出在哪？求救

一般是因为你点太快了，卡片还没有加载完成。你要等一下再点查看更多

**Comment by hxfdean** [comment]
大佬，新问题，装好了，广播有声音，一切正常。搜歌，热歌等听歌没有声音，进度条在走，然后当前广播不会停，你点了暂停按钮，再点歌曲播放的那个小三角，广播又继续播放，就是不能播放歌曲
