### ISSUE TITLE
大佬可以增加苹果safari浏览器支持吗

### ISSUE THREAD

**Issue by gmshiwoge** [shaonianzhentan/cloud_music#36]
苹果safari浏览器和苹果app 点击播放器后 设置 语音 广播 最爱 这几个按钮点击不了
需要谷歌浏览器才可以点击

**Comment by shaonianzhentan** [comment]
> 苹果safari浏览器和苹果app 点击播放器后 设置 语音 广播 最爱 这几个按钮点击不了
> 需要谷歌浏览器才可以点击

抱歉，我没有苹果机，无法调试，所以暂时解决不了

**Comment by renlm520** [comment]
请问下，现在是不是无法登陆网易云啦？我没有登录按钮呢

**Comment by shaonianzhentan** [comment]
> 请问下，现在是不是无法登陆网易云啦？我没有登录按钮呢

登录按钮给隐藏了，只能自己配置

**Comment by shaonianzhentan** [comment]
苹果safari浏览器的问题已经修好了
