### ISSUE TITLE
大佬，集成后广播可以播放，TTS语音正常，就是没法播放网易云api的歌曲，网易云api这边控制台一切正常

### ISSUE THREAD

**Issue by hxfdean** [shaonianzhentan/cloud_music#37]
大佬，集成后广播可以播放，TTS语音正常，就是没法播放网易云api的歌曲，全部都是走进度条，没有声音出来。网易云api这边控制台一切正常，这是怎么回事？望搭救

**Comment by shaonianzhentan** [comment]
> 大佬，集成后广播可以播放，TTS语音正常，就是没法播放网易云api的歌曲，全部都是走进度条，没有声音出来。网易云api这边控制台一切正常，这是怎么回事？望搭救

一般出现这种情况，都是你自己配置的问题，好好看日志细心检查一下，为什么接口不通？是服务没起来？还是服务被隔离了？

**Comment by singer1860** [comment]
Logger: homeassistant
Source: custom_components/ha_cloud_music/api_music.py:444 
First occurred: 下午2:13:54 (5 occurrences) 
Last logged: 下午2:27:19

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/ha_cloud_music/api_voice.py", line 103, in text_event
    await self.api_music.play_list_hotsong(_name)
  File "/config/custom_components/ha_cloud_music/api_music.py", line 444, in play_list_hotsong
    if obj['code'] == 200:
TypeError: 'NoneType' object is not subscriptable
大佬，无法在线搜索听歌，其它都正常。日志代码奉上

**Comment by shaonianzhentan** [comment]
> Logger: homeassistant
> Source: custom_components/ha_cloud_music/api_music.py:444
> First occurred: 下午2:13:54 (5 occurrences)
> Last logged: 下午2:27:19
> 
> Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
> File "/config/custom_components/ha_cloud_music/api_voice.py", line 103, in text_event
> await self.api_music.play_list_hotsong(_name)
> File "/config/custom_components/ha_cloud_music/api_music.py", line 444, in play_list_hotsong
> if obj['code'] == 200:
> TypeError: 'NoneType' object is not subscriptable
> 大佬，无法在线搜索听歌，其它都正常。日志代码奉上

首先先确定接口服务是否正常，如果没问题，再升级到最新版本试试
一般都是接口服务没有正常部署的问题，我已经被问过无数次了
