### ISSUE TITLE
求助登录问题

### ISSUE THREAD

**Issue by zzz929625** [shaonianzhentan/cloud_music#38]
大佬实在不好意思，开个问题来问问怎么登录？
我在前端页面没有登录按钮
![屏幕截图 2021-01-19 230520](https://user-images.githubusercontent.com/49552476/105052472-e3ef8f00-5aaa-11eb-8a3f-0495d6629f65.png)
我开始怀疑是主题的问题，换为官方的也没有，浏览器缓存也清理过
然后我又试了接口登录，STATUS返回CODE200，不知道是不是登录上了，反正后面信息很多，用户名那些也出来了
这个时候我又回前端，但是前端到我的歌单还是提示需要登录，请问这是个啥情况？

**Comment by shaonianzhentan** [comment]
前端的登录按钮被我屏蔽掉了。
你需要配置用户名密码和uid，日志里面会告诉你登录成功。如果登录失败会有提示。

**Comment by zzz929625** [comment]
- platform: ha_cloud_music
    api_url: http://127.0.0.1:3000/
    name: 云音乐

这里面配？原谅我是个小白，UID是啥- -

**Comment by shaonianzhentan** [comment]
> * platform: ha_cloud_music
>   api_url: http://127.0.0.1:3000/
>   name: 云音乐
> 
> 这里面配？原谅我是个小白，UID是啥- -

这是配置文件：uid是网易的用户id
https://github.com/shaonianzhentan/ha_cloud_music/tree/master/docs

**Comment by zzz929625** [comment]
好的我马上试试

**Comment by zzz929625** [comment]
登上去了，非常感谢
