### ISSUE TITLE
hassos core 4.6 ,system 5.13，云音乐有错误

### ISSUE THREAD

**Issue by gmmy1979** [shaonianzhentan/cloud_music#45]
云音乐版本4.6出现以下问题：
1、播放歌曲无声，但播放电台正常
2、拉动进度条提示错误，如下：
 调用服务 media_player/media_seek 失败。expected float for dictionary value@data['seek_position']
 调用服务 media_player/volume_set 失败。expected float for dictionary value@data['volume_level']

请问大佬这个是hassos系统问题还是插件有问题

**Comment by gmmy1979** [comment]
云音乐网易云资源都播放不了，不出声，但电台播放正常、搜索歌曲出来的歌曲，资源是咪咕音乐的又是正常播放的

**Comment by shaonianzhentan** [comment]
> 云音乐网易云资源都播放不了，不出声，但电台播放正常、搜索歌曲出来的歌曲，资源是咪咕音乐的又是正常播放的

应该是你的网易云音乐的接口部署的有问题

**Comment by bossben8** [comment]
升級hassio2021.6.5云音乐版本4.6.1播放歌曲无声,播放电台也无声....

**Comment by shaonianzhentan** [comment]
> 升級hassio2021.6.5云音乐版本4.6.1播放歌曲无声,播放电台也无声....

😢 解决不了，推荐使用其他播放器

**Comment by gmmy1979** [comment]
云音乐只要是网易的资源都播放不了，没声音，电台或QQ音乐播放有声音。api是通过vercel布置的，能正常访问https://dkapi.vercel.app

**Comment by sangood** [comment]
> > 升級hassio2021.6.5云音乐版本4.6.1播放歌曲无声,播放电台也无声....
> 
> 😢 解决不了，推荐使用其他播放器

async def get(self, url):
        link = self.api_url + url
        # 不是登录请求，则显示出来（这里保护登录信息）
        if '/login' not in url:
            print(link)
        result = None
        try:
            global COOKIES            
            jar = aiohttp.CookieJar(unsafe=True)
            connector = aiohttp.TCPConnector(verify_ssl=False)
            async with aiohttp.ClientSession(headers=HEADERS, cookies=COOKIES, cookie_jar=jar, connector=connector) as session:
                async with session.get(link) as resp:

api_music.py 加上connector 试试。其它几个地方也加上

另外老大能否加上 https://github.com/shell-script/telegram-music-bot/blob/master/main.py 这里的酷我音乐无损格式？

另外报告一下，因为api返回的https://music.163.com/song/media/outer/url?id={} .我如果发送到别的机器安装的mpd。需要登录的歌曲没办法播放。能否 如果需要登录的歌曲，替换为酷我的mp3真实URL？

**Comment by gmmy1979** [comment]
> > > 升級hassio2021.6.5云音乐版本4.6.1播放歌曲无声,播放电台也无声....
> > 
> > 
> > 😢 解决不了，推荐使用其他播放器
> 
> async def get(self, url):
> link = self.api_url + url
> # 不是登录请求，则显示出来（这里保护登录信息）
> if '/login' not in url:
> print(link)
> result = None
> try:
> global COOKIES
> jar = aiohttp.CookieJar(unsafe=True)
> connector = aiohttp.TCPConnector(verify_ssl=False)
> async with aiohttp.ClientSession(headers=HEADERS, cookies=COOKIES, cookie_jar=jar, connector=connector) as session:
> async with session.get(link) as resp:
> 
> api_music.py 加上connector 试试。其它几个地方也加上
> 
> 另外老大能否加上 https://github.com/shell-script/telegram-music-bot/blob/master/main.py 这里的酷我音乐无损格式？
> 
> 另外报告一下，因为api返回的[https://music.163.com/song/media/outer/url?id={}](https://music.163.com/song/media/outer/url?id=%7B%7D) .我如果发送到别的机器安装的mpd。需要登录的歌曲没办法播放。能否 如果需要登录的歌曲，替换为酷我的mp3真实URL？


这里添加了，还有哪些地方需要添加的呢
async with aiohttp.ClientSession(headers=HEADERS, cookies=COOKIES, cookie_jar=jar, connector=connector) as session:
> async with session.get(link) as resp:

**Comment by shaonianzhentan** [comment]
> > > 升級hassio2021.6.5云音乐版本4.6.1播放歌曲无声,播放电台也无声....
> > 
> > 
> > 😢 解决不了，推荐使用其他播放器
> 
> async def get(self, url):
> link = self.api_url + url
> # 不是登录请求，则显示出来（这里保护登录信息）
> if '/login' not in url:
> print(link)
> result = None
> try:
> global COOKIES
> jar = aiohttp.CookieJar(unsafe=True)
> connector = aiohttp.TCPConnector(verify_ssl=False)
> async with aiohttp.ClientSession(headers=HEADERS, cookies=COOKIES, cookie_jar=jar, connector=connector) as session:
> async with session.get(link) as resp:
> 
> api_music.py 加上connector 试试。其它几个地方也加上
> 
> 另外老大能否加上 https://github.com/shell-script/telegram-music-bot/blob/master/main.py 这里的酷我音乐无损格式？
> 
> 另外报告一下，因为api返回的[https://music.163.com/song/media/outer/url?id={}](https://music.163.com/song/media/outer/url?id=%7B%7D) .我如果发送到别的机器安装的mpd。需要登录的歌曲没办法播放。能否 如果需要登录的歌曲，替换为酷我的mp3真实URL？

估计是应该HTTPS证书导致的，确实有部分设备在访问HTTPS时异常，
无损音质一般播放器不支持

**Comment by sangood** [comment]
> > > > 升級hassio2021.6.5云音乐版本4.6.1播放歌曲无声,播放电台也无声....
> > > 
> > > 
> > > 😢 解决不了，推荐使用其他播放器
> > 
> > 
> > async def get(self, url):
> > link = self.api_url + url
> > # 不是登录请求，则显示出来（这里保护登录信息）
> > if '/login' not in url:
> > print(link)
> > result = None
> > try:
> > global COOKIES
> > jar = aiohttp.CookieJar(unsafe=True)
> > connector = aiohttp.TCPConnector(verify_ssl=False)
> > async with aiohttp.ClientSession(headers=HEADERS, cookies=COOKIES, cookie_jar=jar, connector=connector) as session:
> > async with session.get(link) as resp:
> > api_music.py 加上connector 试试。其它几个地方也加上
> > 另外老大能否加上 https://github.com/shell-script/telegram-music-bot/blob/master/main.py 这里的酷我音乐无损格式？
> > 另外报告一下，因为api返回的[https://music.163.com/song/media/outer/url?id={}](https://music.163.com/song/media/outer/url?id=%7B%7D) .我如果发送到别的机器安装的mpd。需要登录的歌曲没办法播放。能否 如果需要登录的歌曲，替换为酷我的mp3真实URL？
> 
> 估计是应该HTTPS证书导致的，确实有部分设备在访问HTTPS时异常，
> 无损音质一般播放器不支持
是的，安装了自定义证书。 
酷我也支持高音质mp3的。
