### ISSUE TITLE
使用网页播放器没有声音。。。

### ISSUE THREAD

**Issue by mimokini** [shaonianzhentan/cloud_music#46]
是我设置的问题吗？还是目前只能用MPD？

**Comment by bossben8** [comment]
HA更新後..网页播放器..MPD...所有都没有声音...之前都正常

**Comment by FrostZhang** [comment]
我在linuxdeploy部署hass，音频功能不全，所以使用网页播放器。但是chrome 显示MediaPlayer.js:44   Uncaught (in promise) DOMException: The element has no supported sources.这个好像是浏览器限制了播放功能。有没有解决方案呢？

**Comment by shaonianzhentan** [comment]
这只是一个测试功能，并不是让大家直接使用的，推荐使用MPD服务
