### ISSUE TITLE
可以增加播放本地mp3的服务调用吗？

### ISSUE THREAD

**Issue by jifengmm** [shaonianzhentan/cloud_music#48]
如题，我想在notered中，让我的mpd设备播放本地的某一首歌曲

**Comment by shaonianzhentan** [comment]
> 如题，我想在notered中，让我的mpd设备播放本地的某一首歌曲

音乐文件播放在media/ha_cloud_music目录中，可使用本插件播放本地音乐

**Comment by ghostist** [comment]
他的意思应该是：可以通过调用服务，播放目录指定的文件
我另外问几个问题：
像切换播放器，有没有服务可调用？否则教程视频里说的碰碰贴切换是怎么实现的？

**Comment by shaonianzhentan** [comment]
> 他的意思应该是：可以通过调用服务，播放目录指定的文件
> 我另外问几个问题：
> 像切换播放器，有没有服务可调用？否则教程视频里说的碰碰贴切换是怎么实现的？

他的意思我懂，但没的时间开发。
还有就是本插件的核心是网易云音乐，他的需求应该是要有独立播放本地音乐的服务，本插件并不适用

你的问题通过调用播放器的选择模式服务就可以实现

**Comment by ghostist** [comment]
4.6.1版本的，服务里只有cache、config、load、pick、tts5种服务
cache为缓存音乐
load为加载音乐列表
pick为点歌
tts为TTS
剩下config里包含：
启用语音识别、启用通知、播放模式、播放速度、TTS声音模式、TTS音量、TTS服务前后置消息，没有找到播放器选择模式

**Comment by shaonianzhentan** [comment]
> 4.6.1版本的，服务里只有cache、config、load、pick、tts5种服务
> cache为缓存音乐
> load为加载音乐列表
> pick为点歌
> tts为TTS
> 剩下config里包含：
> 启用语音识别、启用通知、播放模式、播放速度、TTS声音模式、TTS音量、TTS服务前后置消息，没有找到播放器选择模式

media_player.select_sound_mode
