### ISSUE TITLE
最新版如何设置DLAN播放

### ISSUE THREAD

**Issue by Carrjiang** [shaonianzhentan/cloud_music#51]

**Comment by shaonianzhentan** [comment]
在源播放器里选择即可

**Comment by Carrjiang** [comment]
> 在源播放器里选择即可

但是云音乐界面没有相关设置选项，甚至集成内都没有云音乐这个实体。


## System Health

version | core-2021.9.1
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.6
os_name | Linux
os_version | 5.10.0-0.bpo.7-amd64
arch | x86_64
timezone | Asia/Hong_Kong

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4930
Installed Version | 1.15.1
Stage | running
Available Repositories | 946
Installed Repositories | 11

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 10 (buster)
-- | --
update_channel | stable
supervisor_version | supervisor-2021.09.0
docker_version | 20.10.8
disk_total | 13.2 GB
disk_used | 9.7 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.0.1), ZeroTier One (0.11.1), Node-RED (10.0.0), AirSonos (3.1.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 2
views | 1
mode | storage

</details>

**Comment by shaonianzhentan** [comment]
如果是初次使用，请先看视频介绍
安装好之后，在设置中可选择源播放器
![image](https://user-images.githubusercontent.com/5294022/132148948-9144ebd5-2b63-416a-a3c7-9dab55aaa05c.png)

**Comment by Carrjiang** [comment]
> 如果是初次使用，请先看视频介绍
> 安装好之后，在设置中可选择源播放器
> ![image](https://user-images.githubusercontent.com/5294022/132148948-9144ebd5-2b63-416a-a3c7-9dab55aaa05c.png)

好的解决了感谢大佬，但是还有一个问题就是登录账号的话是需要在configure里进行哪些设置呢
