### ISSUE TITLE
HA其他播放器调用无响应

### ISSUE THREAD

**Issue by GWan1234** [shaonianzhentan/cloud_music#52]
感谢老哥的优秀项目，一直在关注和使用，最近看6.3升级很多，
但是只有选择master才能更新，什么时候可以发个Releases呀，
另外有一个问题，我是用的Xiaomi Miot Auto的项目接入的小爱音箱，HA服务里面调用tts没有问题，
自动化播放指定文本也可以使用，但是到云音乐播放选择成小爱的时候，他就无响应，
主要表现为：云音乐播放条进度不动，音乐时长为0，但是切换为网页播放器和mpd播放器之后，一切正常，进度条和音乐时长都出现了。
日志没有报错项目。。。

**Comment by shaonianzhentan** [comment]
不支持小爱音箱

**Comment by GWan1234** [comment]
OK
