### ISSUE TITLE
你好是否可以使用 UnblockNeteaseMusic 来实现播放网易云音乐灰色不能收听歌曲

### ISSUE THREAD

**Issue by gmshiwoge** [shaonianzhentan/cloud_music#56]
路由器是openwrt有UnblockNeteaseMusic使用可以局域网内用网易云音乐听周杰伦歌曲

**Comment by shaonianzhentan** [comment]
[find-music](https://github.com/shaonianzhentan/find-music) 项目是这个插件的解决方案

**Comment by gmshiwoge** [comment]
谢谢 我使用node docker容器  终端来安装find-music的  请问一下有什么方法可以在启动 node docker容器后 自动输入 
cd find-music 
pm2 start index.js --name findmusic启动呢

**Comment by shaonianzhentan** [comment]
需要单独安装，没有docker版本
