### ISSUE TITLE
本地音乐似乎只能播放顶级目录的歌曲

### ISSUE THREAD

**Issue by vincywindy** [shaonianzhentan/cloud_music#57]
在docker把音乐目录映射到config的media里面，是能看见歌曲的，但是只能看到顶层目录的歌曲，如果有子目录的话似乎不能递归查找，导致一些归好类的音乐无法播放

**Comment by shaonianzhentan** [comment]
目前这一块设计的比较简单，一键播放当前目录下的音乐，不会读取子目录下的文件

**Comment by hdinson** [comment]
> 目前这一块设计的比较简单，一键播放当前目录下的音乐，不会读取子目录下的文件

是否有递归查找的计划呢
