### ISSUE TITLE
播放本地音乐问题

### ISSUE THREAD

**Issue by HASSAAS** [shaonianzhentan/cloud_music#58]
你好！  播放本地音乐 提示媒体浏览错误 ，请问是啥问题呢

**Comment by HASSAAS** [comment]
![微信截图_20211107084921](https://user-images.githubusercontent.com/90961911/140628192-ec10f93b-130d-4b44-9330-a7d2adf47789.png)

**Comment by shaonianzhentan** [comment]
![image](https://user-images.githubusercontent.com/5294022/141405620-7b8755ae-8883-47d9-9b4f-c433a912cd9c.png)
最好提供一下日志之类的，或者先自行排错一下😂我没有看图识BUG的功能，这样我也一脸懵
