### ISSUE TITLE
源播放器列表是否可以自定义

### ISSUE THREAD

**Issue by wyh260595711** [shaonianzhentan/cloud_music#59]
首先多谢大神能提供这么优秀的插件，用下来也很棒，有几个问题我想问一下或者说提供一些建议。
第一个是源播放器列表是否可以自定义:现在是所有HA中的media_player.xxx都会收录进来，是否可以进行自定义，让用户把有需要播放音乐的媒体播放器留下，不需要的剔除。
第二个是音乐播放的通知是否可以选择关闭不通知:这个纯不同用户的习惯，我就一问哈。
第三个是添加到homekit中后的输入源列表问题:现在是把‘正在播放’的列表接到了homekit中的输入源列表，如果列表歌曲太多会导致添加失败，如果可以的话可以把插件中的源播放器列表对接到homekit的输出源列表。
再次感谢作者大神。

**Comment by shaonianzhentan** [comment]
感谢你的建议，我翻了一下代码得出以下结论😂
1. 因为更换频率不高，所以不会考虑自定义的情况（可以自己定义select实体通过调用服务实现）
2. 在设置服务中有关闭通知的选项，在非错误的情况下不通知提示
3. 我考虑了一下，这个只在HomeKit里会出现这种问题，如果变动会对HA和TileBoard有影响，导致无法方便的切换的音乐

**Comment by wyh260595711** [comment]
那大神，第三点有没有什么好的办法可以实现？我曲线救国也行，比如自己创建Universal Media Player等方法？虽然这已经和您改进插件没关系了，但是还是请大神指条明路，谢谢啦

**Comment by shaonianzhentan** [comment]
主要是我不能判断是否HomeKit接入，不然直接就处理了
其实我的想法是使用那个HomeKit遥控器，控制音量和上一曲下一曲之类的，根本就不会在HomeKit里去使用那个没啥用的媒体组件，音乐数量多了，确实卡的不行
