### ISSUE TITLE
播放本地音乐没有进度显示，导致无法切换到下一首

### ISSUE THREAD

**Issue by koolca** [shaonianzhentan/cloud_music#61]
如题，找了一圈只有ha_cloud_music最合适播放本地音乐，但目前播放完一首mp3之后就停止播放了，望作者解决，谢谢

**Comment by koolca** [comment]
提示调用服务media_player/media_seek失败

**Comment by shaonianzhentan** [comment]
这个应该是因为源播放器不支持进度调节功能，所以导致无法自动下一曲

**Comment by koolca** [comment]
看来暂时无解了，仍然感谢 @shaonianzhentan
