### ISSUE TITLE
删除单曲/清空歌曲列表失败

### ISSUE THREAD

**Issue by tangli159** [shaonianzhentan/cloud_music#62]
你好，我删除某个单曲
![image](https://user-images.githubusercontent.com/50565072/153704803-d0b9bce4-eea9-493c-869d-9a70eb8545a9.png)

或者清空歌曲列表全部都会失败，请问要怎么解决呢
![image](https://user-images.githubusercontent.com/50565072/153704518-3e3413db-d13c-4d13-9b93-ff57b069f288.png)

查看日志只有这一个报错。
![image](https://user-images.githubusercontent.com/50565072/153704970-d0ee9df8-1ba5-4101-89ec-bf06618ea9d2.png)

**Comment by shaonianzhentan** [comment]
😂已经提示不支持了啊

**Comment by tangli159** [comment]
抱歉！
