### ISSUE TITLE
无法播放网易云vip音乐

### ISSUE THREAD

**Issue by konglinSoul** [shaonianzhentan/cloud_music#63]
大佬你好 登录了我的账号后无法播放vip歌曲 直接调用api登录后是可以播放
![Quicker_20220225_224029](https://user-images.githubusercontent.com/48609186/155734456-158e0fb7-fda4-468c-a985-862310925018.png)
![Quicker_20220225_223914](https://user-images.githubusercontent.com/48609186/155734469-fd44bbbb-2afa-4da8-8b46-be687ef28028.png)
的

**Comment by konglinSoul** [comment]
修改了一下代码测试发现是url为空 但是用电脑浏览器调用接口是正常的 大佬知道是为什么吗
![Quicker_20220227_010757](https://user-images.githubusercontent.com/48609186/155852466-1ce37bc9-0542-4da8-9aab-ebac77d583a0.png)
![Quicker_20220227_010836](https://user-images.githubusercontent.com/48609186/155852467-a47e1dfa-f811-4f1b-a5f5-6023b83fa9d8.png)

![Quicker_20220227_010901](https://user-images.githubusercontent.com/48609186/155852470-2be6d2d3-e7c6-452d-859e-58e5fbccfa86.png)

**Comment by shaonianzhentan** [comment]
如果是VIP音乐，那应该和登录Cookie有关。
我没有VIP账号，所以没有测试相关功能

**Comment by konglinSoul** [comment]
> 如果是VIP音乐，那应该和登录Cookie有关。 我没有VIP账号，所以没有测试相关功能

好的 谢谢大佬 请问4.7.3发布了吗 我在hacs搜索不到云音乐 git下载不到

**Comment by shaonianzhentan** [comment]
我的所有项目都没有加入到HACS官方库中，需要使用自定义方式安装

**Comment by konglinSoul** [comment]
> 我的所有项目都没有加入到HACS官方库中，需要使用自定义方式安装

好的 我发现用 在 api_music.py中获取歌单列表里的 "url": "https://music.163.com/song/media/outer/url?id=" + str(item['id']) + ".mp3",  无法获取到vip歌曲（登录了也不行） 如果是非vip歌曲则可以 请问大佬可以怎么改成用ip：3000/song/url?id的返回的url来获取歌曲吗 我不会用py尝试改了一下没7有成功
![Quicker_20220228_191653](https://user-images.githubusercontent.com/48609186/155974395-ecfb5020-63bf-4dae-87de-44fc2611f88b.png)

**Comment by shaonianzhentan** [comment]
建议fork代码，然后根据自己的需求进行修改
