### ISSUE TITLE
mmplayer 原版的可以在手机播放，这个就不行

### ISSUE THREAD

**Issue by ritech** [shaonianzhentan/cloud_music#65]
云音乐选择网页播放器，在iphone 手机上放完全没声音
mmplayer 原版没这个问题

**Comment by ritech** [comment]
语音小助手更新后
播放器内部的指令无法使用
ha_cloud_music.hass.callApi('POST', 'events/ha_voice_text_event', { text: value }).then(res => {
                ha_cloud_music.toast("命令发送成功")

代码还是调用的以前的语音助手方式

**Comment by shaonianzhentan** [comment]
去gitee上下载最新版
