### ISSUE TITLE
homeassistent 安装了最新版，pc（edge浏览器）网页，和手机（iphonexr）还是没有声音

### ISSUE THREAD

**Issue by corbettbain** [shaonianzhentan/cloud_music#67]
插件安装后，点击云音乐可以看见进度条和封面正长。， 进度条也正常，就是没有声音，如图：

![2022-05-04 11-09-15](https://user-images.githubusercontent.com/25195955/166618463-ee7400c8-e749-4ae0-bf7a-eeea8bf25137.png)

每次刷新了页面或者重新打开  都要切换下源播放器， 先切换到别的    然后在切换回网页播放器就有声音了

![2022-05-04 11-10-44](https://user-images.githubusercontent.com/25195955/166618533-ceb174e3-647b-45e1-9040-7bf557061d6b.png)

**Comment by ritech** [comment]
要反复切几次 才能有声音，你可以windows播放器和网页播放器之间来回切
这个还真是个bug，默认的播放源和网页上并不匹配，或者把默认的源可以写在configuration里面

**Comment by shaonianzhentan** [comment]
#46 这是一个用来测试的功能而已
