### ISSUE TITLE
4.7.4 播放格式支持问题

### ISSUE THREAD

**Issue by hdinson** [shaonianzhentan/cloud_music#68]
是否支持ape，flac格式的音乐文件，经测试mp3的格式能识别
![image](https://user-images.githubusercontent.com/17812321/180760371-f8049dbb-22bb-4d64-b5af-ff6247e4e729.png)
![image](https://user-images.githubusercontent.com/17812321/180760473-e97d0e27-b29e-44f0-9b8a-d3cbd0b82795.png)

**Comment by shaonianzhentan** [comment]
部分播放设备不支持这种格式😅
