### ISSUE TITLE
网页播放器播放本地文件的url设置错误

### ISSUE THREAD

**Issue by vincywindy** [shaonianzhentan/cloud_music#69]
![image](https://user-images.githubusercontent.com/30209724/186304830-bf502ac7-510b-4ef6-8d34-4241478c9d59.png)
如图所示，我的ha走了一个反向代理，插件调用了局域网的url，因此肯定无法播放，建议配置里面增加一个访问url的配置项，来设置ha正确的访问url

**Comment by livebelive** [comment]
我也使用了反向代理 一直无法连接API 你是怎么解决的？

**Comment by shaonianzhentan** [comment]
不考虑特殊网络环境，建议自行fork代码修改适配
