### ISSUE TITLE
老大可以做一个0.9.3版本的吗

### ISSUE THREAD

**Issue by gmshiwoge** [shaonianzhentan/cloud_music#7]
0.9.3安装没有左侧栏进去操作

**Comment by shaonianzhentan** [comment]
> 0.9.3安装没有左侧栏进去操作

兄弟，你这版本落后有点严重啊，现在都0.106.1了啊

2.3.6版本尝试解决这个问题，你可以试试

**Comment by gmshiwoge** [comment]
老大 已经更新到2.3.6 还是没有左侧栏

**Comment by shaonianzhentan** [comment]
> 老大 已经更新到2.3.6 还是没有左侧栏

那你就自己加一个：  /ha_cloud_music-local/2.3.6/index.html
那个2.3.6是你安装的版本号

**Comment by gmshiwoge** [comment]
panel_iframe:
  configurator:
    title: 云音乐
    icon: mdi:music
    url: 'http://192.168.50.244:8123/ha_cloud_music-local/2.3.6/index.html'
谢谢 通过这个方式可以使用  但是在外网访问 ha使用不了 已经转发8123端口了

**Comment by gmshiwoge** [comment]
请问下 tts怎么使用  安装完网易云音乐后， 我本安装的tts使用不了了

**Comment by shaonianzhentan** [comment]
> 请问下 tts怎么使用 安装完网易云音乐后， 我本安装的tts使用不了了

这个服务：ha_cloud_music.tts

**Comment by gmshiwoge** [comment]
你好 今日把ha升级到  Home Assistant 0.106.6版本 安装v2.3.6  不能正常使用 工具连接不了服务器一直在转圈，tts服务也没有

**Comment by gmshiwoge** [comment]
老大 安装最新版ha 发现播放完歌曲不能自动却换下一首歌

**Comment by gmshiwoge** [comment]
现在Home Assistant 0.106.6  mpd播放器 播放完不会切歌
