### ISSUE TITLE
密码输入对了的，但还是提示账号密码错误，估计是接口有问题了

### ISSUE THREAD

**Issue by Seifon** [shaonianzhentan/cloud_music#70]
云音乐
网易云登录失败，请检查账号密码是否错误。如果确定没错，请检查接口是否正常。

**Comment by shaonianzhentan** [comment]
请自行部署接口

**Comment by maohouzi** [comment]
请教一下，就是云音乐在ha里面都能用，就是没法同步我网易云音乐的歌单，叫登录，我的netease_cloud_music_api都能正常跑数据，这个自行部署登录接口，一直没找到在什么地方部署。

**Comment by shaonianzhentan** [comment]
> 请教一下，就是云音乐在ha里面都能用，就是没法同步我网易云音乐的歌单，叫登录，我的netease_cloud_music_api都能正常跑数据，这个自行部署登录接口，一直没找到在什么地方部署。

关于接口的所有问题，请参考netease_cloud_music_api提供的文档：https://neteasecloudmusicapi.vercel.app

**Comment by maohouzi** [comment]
- platform: ha_cloud_music
    api_url: 'http://localhost:3000'
    user: 网易云账号(邮箱或手机号)
    passwowrd: 网易云密码

难道这里不是调用接口的地方？
