### ISSUE TITLE
4.7版本后是否还有手动安装的办法

### ISSUE THREAD

**Issue by wxue1011** [shaonianzhentan/cloud_music#72]
安装的时候确实可以看见\custom_components\ha_cloud_music确实被下载下来了，但Hacs现实一直安装中，几个小时都还在安装中，所以想请教下是否还有手动安装的办法，谢谢

不知道是不是还没有对应最新的环境，我的环境如下：
Home Assistant 2022.10.3
Supervisor 2022.10.0
Operating System 9.2
前端版本： 20221010.0 - latest

**Comment by shaonianzhentan** [comment]
可以使用多种方式进行安装，可以关注项目底部的微信公众号，学习一下HA的基本知识
